// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9exzG1GT62JcZadLz4owTA
// Component: 3p1beTTXOe
import * as React from "react";
import Head from "next/head";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import NavTop from "../../NavTop"; // plasmic-import: eCdmC84KTs/component
import Footer from "../../Footer"; // plasmic-import: qmi9gzc5EPV/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_xiang_portfolio.module.css"; // plasmic-import: 9exzG1GT62JcZadLz4owTA/projectcss
import * as sty from "./PlasmicComingSoon.module.css"; // plasmic-import: 3p1beTTXOe/css

export const PlasmicComingSoon__VariantProps = new Array();

export const PlasmicComingSoon__ArgProps = new Array();

function PlasmicComingSoon__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <Head>
        <title key="title">{""}</title>
        <meta key="og:title" property="og:title" content={""} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <NavTop
            data-plasmic-name={"navTop"}
            data-plasmic-override={overrides.navTop}
            className={classNames("__wab_instance", sty.navTop)}
          />

          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(defaultcss.all, sty.freeBox)}
          />

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "navTop", "freeBox", "footer"],
  navTop: ["navTop"],
  freeBox: ["freeBox"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicComingSoon__ArgProps,
      internalVariantPropNames: PlasmicComingSoon__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicComingSoon__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicComingSoon";
  } else {
    func.displayName = `PlasmicComingSoon.${nodeName}`;
  }
  return func;
}

export const PlasmicComingSoon = Object.assign(
  // Top-level PlasmicComingSoon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navTop: makeNodeComponent("navTop"),
    freeBox: makeNodeComponent("freeBox"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicComingSoon
    internalVariantProps: PlasmicComingSoon__VariantProps,
    internalArgProps: PlasmicComingSoon__ArgProps
  }
);

export default PlasmicComingSoon;
/* prettier-ignore-end */
